name: on push

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=sha,prefix=
            type=raw,value=latest

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode clean test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - name: update tags in helm values files
#        run: |
#          sed -i "s,tag:.*,tag:\ ${GITHUB_SHA::7}," k8s/helm-values/k3d-devt-values.yaml
#          if [ $GITHUB_REF_NAME == 'main' ]; then
#            echo "update test values"
#            sed -i "s,tag:.*,tag:\ ${GITHUB_SHA::7}," k8s/helm-values/k3d-test-values.yaml
#            echo "update acpt values"
#            sed -i "s,tag:.*,tag:\ ${GITHUB_SHA::7}," k8s/helm-values/k3d-acpt-values.yaml
#          fi
#
#      - uses: EndBug/add-and-commit@v7
#        with:
#          default_author: github_actions



